server:
  port: 8015 # 端口
  tomcat:
    max-threads: 10 # 降低最大线程数方便模拟高并发

  # compression:
      # 是否开启压缩
     #  enabled: true
      # 配置压缩支持的 MIME TYPE
     #  mime-types: application/json,application/xml,text/html,text/xml,text/plain

feign:
  httpclient:
    enabled: true # 开启 httpclient
  hystrix:
    enabled: true # 开启内置熔断器

# 配置 Eureka Server 注册中心
eureka:
  client:
    register-with-eureka: true         # 是否将自己注册到注册中心，默认为 true
    registry-fetch-interval-seconds: 10 # 表示 Eureka Client 间隔多久去服务器拉取注册信息，默认为 30 秒
    service-url:                        # 设置服务注册中心地址
      defaultZone:  http://root:123456@swapping2:8012/eureka/,http://root:123456@swapping1:8011/eureka/
      #,http://swapping2:8021/eureka/,http://swapping3:8031/eureka/

# 负载均衡策略
service-hi: # 调用的服务的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 随机策略，默认是轮询策略
    # service-provider 是需要调用的服
    OkToRetryOnAllOperations: true  # 对所有请求都进行重试
    MaxAutoRetries: 2                        # 对当前实例的重试次数
    MaxAutoRetriesNextServer: 0     # 切换实例的重试次数
    ConnectTimeout: 3000                # 请求连接的超时时间
    ReadTimeout: 3000                     # 请求处理的超时时间

#配置数据源
spring:
  application:
      name: service-consumer # 应用名称
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://127.0.0.1:3306/sales?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: 1

      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  #配置 Jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: update

  # redis 缓存
  redis:
    timeout: 10000        # 连接超时时间
    host: 127.0.0.1  # Redis服务器地址
    port: 6379            # Redis服务器端口
    password: 1        # Redis服务器密码
    database: 0           # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024  # 最大连接数，默认 8
        max-wait: 10000   # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200     # 最大空闲连接，默认 8
        min-idle: 5       # 最小空闲连接，默认 0

# 度量指标监控与健康检查
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream